repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Path to your docs
        - --hook-config=--add-to-existing-file=true     # Add to existing README.md
        - --hook-config=--create-file-if-not-exist=true # Create README.md if not exists
    - id: terraform_tflint
      args:
        - '--args=--only=terraform_deprecated_interpolation'
        - '--args=--only=terraform_deprecated_index'
        - '--args=--only=terraform_unused_declarations'
        - '--args=--only=terraform_comment_syntax'
        - '--args=--only=terraform_documented_outputs'
        - '--args=--only=terraform_documented_variables'
        - '--args=--only=terraform_typed_variables'
        - '--args=--only=terraform_naming_convention'
        - '--args=--only=terraform_required_version'
        - '--args=--only=terraform_required_providers'
    - id: terraform_validate
